import { Product, Order, EmergencyInquiry } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  // ==========================================
  // 1. CATERPILLAR FORKLIFT SPARE PARTS
  // ==========================================
  // Engine
  {
    id: 'cat-1',
    part_number: 'C-1505-CAT',
    name: 'Engine Oil Filter Sakura C-1505 / Isuzu OEM',
    brand: 'Caterpillar',
    category: 'Filter',
    compatible_models: ['Caterpillar DP20', 'Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar DP35'],
    price: 185000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80',
    description: 'Filter oli mesin Sakura C-1505 OEM Caterpillar DP25/DP30. Menyaring kotoran dan jelaga pelumasan mesin.',
    is_fast_moving: true,
    created_at: new Date('2026-01-10').toISOString(),
  },
  {
    id: 'cat-2',
    part_number: 'F-1502-CAT',
    name: 'Fuel Filter Element Sakura F-1502 / Isuzu OEM',
    brand: 'Caterpillar',
    category: 'Filter',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 210000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    description: 'Elemen filter solar bahan bakar Sakura F-1502 untuk mesin diesel Caterpillar. Suplai solar bersih ke bospom.',
    is_fast_moving: true,
    created_at: new Date('2026-01-12').toISOString(),
  },
  {
    id: 'cat-3',
    part_number: '91361-00800',
    name: 'Air Filter Element Set Sakura A-1502/A-1503 (Outer/Inner)',
    brand: 'Caterpillar',
    category: 'Filter',
    compatible_models: ['Caterpillar DP20', 'Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 320000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80',
    description: 'Set filter udara luar dan dalam Sakura A-1502/A-1503 untuk perlindungan ganda mesin Caterpillar.',
    is_fast_moving: true,
    created_at: new Date('2026-01-15').toISOString(),
  },
  {
    id: 'cat-4',
    part_number: 'V-BELT-A38-CAT',
    name: 'Engine Fan Belt V-Belt Heavy Duty Tipe A38',
    brand: 'Caterpillar',
    category: 'Engine',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Mitsubishi S4S'],
    price: 95000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'V-belt tali kipas mesin diesel Caterpillar tipe A38 berbahan sintetis tahan panas gesekan kontinyu.',
    is_fast_moving: true,
    created_at: new Date('2026-01-18').toISOString(),
  },
  {
    id: 'cat-5',
    part_number: '11065-CAT',
    name: 'Glow Plug Busi Pemanas Diesel 12V',
    brand: 'Caterpillar',
    category: 'Engine',
    compatible_models: ['Caterpillar DP20', 'Caterpillar DP25', 'Caterpillar DP30'],
    price: 240000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Busi pemanas (glow plug) 12V starter mesin diesel Caterpillar saat kondisi suhu mesin dingin.',
    is_fast_moving: true,
    created_at: new Date('2026-01-20').toISOString(),
  },
  {
    id: 'cat-6',
    part_number: '91446-10010',
    name: 'Engine Water Pump Assembly Mitsubishi S4S',
    brand: 'Caterpillar',
    category: 'Engine',
    compatible_models: ['Caterpillar DP20', 'Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar DP35'],
    price: 1650000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Pompa air pendingin (water pump) mesin S4S Caterpillar DP25/DP30. Menjaga sirkulasi air radiator.',
    is_fast_moving: true,
    created_at: new Date('2026-01-22').toISOString(),
  },
  {
    id: 'cat-7',
    part_number: '32B45-10030',
    name: 'Engine Thermostat 76.5°C Assembly',
    brand: 'Caterpillar',
    category: 'Engine',
    compatible_models: ['Caterpillar DP20', 'Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar DP50'],
    price: 290000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Thermostat pengatur suhu air pendingin mesin Caterpillar. Membuka pada 76.5°C cegah overheat.',
    is_fast_moving: true,
    created_at: new Date('2026-01-25').toISOString(),
  },
  {
    id: 'cat-8',
    part_number: '093400-CAT',
    name: 'Fuel Injector Nozzle Solar Diesel',
    brand: 'Caterpillar',
    category: 'Engine',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar DP35'],
    price: 450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Nozzle injektor bahan bakar solar presisi tinggi untuk pembakaran optimal mesin Caterpillar.',
    is_fast_moving: true,
    created_at: new Date('2026-01-28').toISOString(),
  },
  {
    id: 'cat-9',
    part_number: '5-87813-CAT',
    name: 'Engine Piston Kit Set Complete (Piston, Ring, Pin)',
    brand: 'Caterpillar',
    category: 'Engine',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar DP35'],
    price: 2850000,
    stock_status: 'INDENT',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Set piston mesin komplit (Piston, Ring, Pin) untuk overhaul mesin diesel Caterpillar.',
    is_fast_moving: false,
    created_at: new Date('2026-02-01').toISOString(),
  },
  {
    id: 'cat-10',
    part_number: 'ME014833-CAT',
    name: 'Engine Gasket Overhaul Set Top & Bottom',
    brand: 'Caterpillar',
    category: 'Engine',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar DP35'],
    price: 1450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Paking set overhaul komplit berbahan baja berlapis grafit presisi tinggi Caterpillar.',
    is_fast_moving: false,
    created_at: new Date('2026-02-02').toISOString(),
  },
  // Transmission
  {
    id: 'cat-11',
    part_number: '91366-01300',
    name: 'Torque Converter Transmission Oil Filter',
    brand: 'Caterpillar',
    category: 'Filter',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar DP35', 'Caterpillar DP50'],
    price: 495000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80',
    description: 'Filter oli transmisi otomatis (Powershift Torque Converter) forklift Caterpillar.',
    is_fast_moving: true,
    created_at: new Date('2026-02-03').toISOString(),
  },
  {
    id: 'cat-12',
    part_number: '91446-00600',
    name: 'Transmission Clutch Disc Friction Plate',
    brand: 'Caterpillar',
    category: 'Brake',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 480000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Plat kopling transmisi (friction disc) berbahan bronze-metalik tahan gesekan tinggi Caterpillar.',
    is_fast_moving: true,
    created_at: new Date('2026-02-04').toISOString(),
  },
  {
    id: 'cat-13',
    part_number: '91366-CAT-KIT',
    name: 'Automatic Transmission Repair Seal Kit',
    brand: 'Caterpillar',
    category: 'Brake',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar DP35'],
    price: 890000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Sil kit perbaikan transmisi otomatis Powershift Caterpillar mencegah kebocoran oli transmisi.',
    is_fast_moving: true,
    created_at: new Date('2026-02-05').toISOString(),
  },
  {
    id: 'cat-14',
    part_number: '91A46-10100',
    name: 'Brake Master Cylinder Assembly',
    brand: 'Caterpillar',
    category: 'Brake',
    compatible_models: ['Caterpillar DP20', 'Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 1450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Master rem utama presisi tinggi untuk unit forklift Caterpillar kapasitas 2.0 - 3.0 Ton.',
    is_fast_moving: true,
    created_at: new Date('2026-02-06').toISOString(),
  },
  {
    id: 'cat-15',
    part_number: '91446-00900',
    name: 'Wheel Brake Cylinder Assembly Left/Right',
    brand: 'Caterpillar',
    category: 'Brake',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25', 'Caterpillar GP30'],
    price: 450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Silinder roda pengereman tromol depan forklift Caterpillar dilengkapi seal anti bocor.',
    is_fast_moving: true,
    created_at: new Date('2026-02-07').toISOString(),
  },
  {
    id: 'cat-16',
    part_number: '91B46-10313',
    name: 'Brake Shoe Set Front Heavy Duty',
    brand: 'Caterpillar',
    category: 'Brake',
    compatible_models: ['Caterpillar DP20', 'Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 780000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Kampas rem set roda depan forklift Caterpillar DP25 & DP30 daya cengkeram tinggi.',
    is_fast_moving: true,
    created_at: new Date('2026-02-08').toISOString(),
  },
  // Hydraulic & Mast
  {
    id: 'cat-17',
    part_number: '91366-04100',
    name: 'Hydraulic Return Oil Filter Element',
    brand: 'Caterpillar',
    category: 'Hydraulic',
    compatible_models: ['Caterpillar DP20', 'Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 420000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Elemen filter oli hidrolik saluran balik (return line) forklift Caterpillar menyaring hingga 10 mikron.',
    is_fast_moving: true,
    created_at: new Date('2026-02-09').toISOString(),
  },
  {
    id: 'cat-18',
    part_number: '91E65-02100',
    name: 'Tilt Cylinder Seal Kit Heavy Duty',
    brand: 'Caterpillar',
    category: 'Hydraulic',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar DP35'],
    price: 680000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Kit seal silinder tilt (karet sil kemiringan mast) Caterpillar wiper seal & O-ring.',
    is_fast_moving: true,
    created_at: new Date('2026-02-10').toISOString(),
  },
  {
    id: 'cat-19',
    part_number: '91465-01500',
    name: 'Main Lift Cylinder Seal Repair Kit',
    brand: 'Caterpillar',
    category: 'Hydraulic',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30'],
    price: 850000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Repair kit seal silinder angkat utama Caterpillar. Mencegah penurunan garpu saat bawa beban.',
    is_fast_moving: true,
    created_at: new Date('2026-02-11').toISOString(),
  },
  {
    id: 'cat-20',
    part_number: 'MG307-CAT',
    name: 'Mast Roller Bearing Heavy Duty',
    brand: 'Caterpillar',
    category: 'Hydraulic',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 380000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Bearing roller pada rel tiang mast Caterpillar tahan beban vertikal hingga 3.5 Ton.',
    is_fast_moving: true,
    created_at: new Date('2026-02-12').toISOString(),
  },
  {
    id: 'cat-21',
    part_number: 'LH1044-CAT',
    name: 'Lifting Chain Rantai Angkat Mast 5 Meter',
    brand: 'Caterpillar',
    category: 'Hydraulic',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar DP35'],
    price: 1750000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Rantai angkat (lifting chain) mast Caterpillar tipe LH1044 panjang 5 meter baja alloy.',
    is_fast_moving: false,
    created_at: new Date('2026-02-13').toISOString(),
  },
  {
    id: 'cat-22',
    part_number: 'CW-CAT-14T',
    name: 'Chain Wheel Sprocket Gear Rantai Mast',
    brand: 'Caterpillar',
    category: 'Hydraulic',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30'],
    price: 520000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Roda puli gear rantai angkat (chain wheel sprocket) tiang mast Caterpillar 3 Ton.',
    is_fast_moving: false,
    created_at: new Date('2026-02-14').toISOString(),
  },
  {
    id: 'cat-23',
    part_number: '214A2-CAT',
    name: 'Hydraulic Gear Pump Assembly 250 Bar',
    brand: 'Caterpillar',
    category: 'Hydraulic',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 3650000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Pompa hidrolik utama (Gear pump) Caterpillar 3 Ton tekanan fluida hingga 250 Bar.',
    is_fast_moving: true,
    created_at: new Date('2026-02-15').toISOString(),
  },
  {
    id: 'cat-24',
    part_number: 'CV-3S-CAT',
    name: 'Hydraulic Control Valve Assembly 3-Spool',
    brand: 'Caterpillar',
    category: 'Hydraulic',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30'],
    price: 4950000,
    stock_status: 'INDENT',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Katup kontrol distribusi hidrolik (Control valve 3-spool) pengatur lift tilt Caterpillar.',
    is_fast_moving: false,
    created_at: new Date('2026-02-16').toISOString(),
  },
  // Steering & Chassis
  {
    id: 'cat-25',
    part_number: '91343-00200',
    name: 'Steering Axle Knuckle Left/Right',
    brand: 'Caterpillar',
    category: 'Hydraulic',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 1850000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Steering knuckle (komponen setir roda belakang) Caterpillar besi tuang heavy-duty.',
    is_fast_moving: false,
    created_at: new Date('2026-02-17').toISOString(),
  },
  {
    id: 'cat-26',
    part_number: '91443-CAT',
    name: 'Steering Tie Rod End Ball Joint',
    brand: 'Caterpillar',
    category: 'Hydraulic',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 540000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Tie rod end (sambungan setir kemudi) roda belakang Caterpillar meminimalkan speling.',
    is_fast_moving: true,
    created_at: new Date('2026-02-18').toISOString(),
  },
  {
    id: 'cat-27',
    part_number: '91343-00100',
    name: 'Steering Axle Kingpin & Bearing Repair Kit',
    brand: 'Caterpillar',
    category: 'Hydraulic',
    compatible_models: ['Caterpillar DP20', 'Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 1120000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Kit perbaikan king pin (as putar roda kemudi) bearing thrust & bushing Caterpillar.',
    is_fast_moving: true,
    created_at: new Date('2026-02-19').toISOString(),
  },
  {
    id: 'cat-28',
    part_number: '30209-CAT',
    name: 'Front/Rear Wheel Tapered Roller Bearing',
    brand: 'Caterpillar',
    category: 'Brake',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 275000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Bearing roda (wheel bearing) tapered roller presisi tinggi Caterpillar.',
    is_fast_moving: true,
    created_at: new Date('2026-02-20').toISOString(),
  },
  {
    id: 'cat-29',
    part_number: 'TIRE-700-12-CAT',
    name: 'Solid Forklift Tire 7.00-12 Industrial Heavy Duty',
    brand: 'Caterpillar',
    category: 'Hydraulic',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 2450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Ban mati (Solid Tire) forklift Caterpillar 7.00-12 bebas bocor tahan paku.',
    is_fast_moving: true,
    created_at: new Date('2026-02-21').toISOString(),
  },
  // Electrical
  {
    id: 'cat-30',
    part_number: '32B66-00100',
    name: 'Starter Motor Assembly 12V 2.8kW Heavy Duty',
    brand: 'Caterpillar',
    category: 'Electrical',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar DP35'],
    price: 3200000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Motor starter 12 Volt 2.8kW torsi tinggi untuk menghidupkan mesin diesel Caterpillar.',
    is_fast_moving: true,
    created_at: new Date('2026-02-22').toISOString(),
  },
  {
    id: 'cat-31',
    part_number: '32A68-00800',
    name: 'Alternator Assembly 12V 50A Heavy Duty',
    brand: 'Caterpillar',
    category: 'Electrical',
    compatible_models: ['Caterpillar DP20', 'Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 2850000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Alternator pengisian aki 12 Volt 50 Ampere heavy-duty IC regulator Caterpillar.',
    is_fast_moving: true,
    created_at: new Date('2026-02-23').toISOString(),
  },
  {
    id: 'cat-32',
    part_number: 'ACCU-12V70AH-CAT',
    name: 'Forklift Heavy Duty Battery Accu 12V 70Ah',
    brand: 'Caterpillar',
    category: 'Electrical',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 1350000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Aki/Battery forklift 12 Volt 70Ah CCA tinggi tahan getaran Caterpillar.',
    is_fast_moving: true,
    created_at: new Date('2026-02-24').toISOString(),
  },
  {
    id: 'cat-33',
    part_number: '91A28-10010',
    name: 'Ignition Starter Key Switch Assembly',
    brand: 'Caterpillar',
    category: 'Electrical',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 350000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Kunci kontak starter (Ignition Key Switch) komplit dengan 2 kunci serep Caterpillar.',
    is_fast_moving: true,
    created_at: new Date('2026-02-25').toISOString(),
  },
  {
    id: 'cat-34',
    part_number: 'LAMP-LED-CAT',
    name: 'Forklift Front Headlamp & Rear Tail Lamp LED Set 24V',
    brand: 'Caterpillar',
    category: 'Electrical',
    compatible_models: ['Caterpillar DP25', 'Caterpillar DP30', 'Caterpillar GP25'],
    price: 420000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Set lampu depan LED dan lampu belakang kombinasi 24V Caterpillar hemat energi.',
    is_fast_moving: true,
    created_at: new Date('2026-02-26').toISOString(),
  },

  // ==========================================
  // 2. KOMATSU FORKLIFT SPARE PARTS
  // ==========================================
  {
    id: 'kom-1',
    part_number: 'C-1505-KOM',
    name: 'Engine Oil Filter Sakura C-1505 / Isuzu OEM',
    brand: 'Komatsu',
    category: 'Filter',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16', 'Komatsu FD35T-10'],
    price: 185000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80',
    description: 'Filter oli mesin Sakura C-1505 OEM Komatsu FD25/FD30. Menyaring kotoran pelumasan.',
    is_fast_moving: true,
    created_at: new Date('2026-01-10').toISOString(),
  },
  {
    id: 'kom-2',
    part_number: '600-211-1340',
    name: 'Fuel Filter Element Main Komatsu Genuine',
    brand: 'Komatsu',
    category: 'Filter',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16', 'Komatsu PC200-8'],
    price: 375000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    description: 'Elemen filter bahan bakar utama Komatsu Genuine Part suplai solar bersih.',
    is_fast_moving: true,
    created_at: new Date('2026-01-12').toISOString(),
  },
  {
    id: 'kom-3',
    part_number: 'A-1502',
    name: 'Air Filter Element Set Sakura A-1502/A-1503 (Outer/Inner)',
    brand: 'Komatsu',
    category: 'Filter',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16', 'Komatsu FD35T-10'],
    price: 320000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80',
    description: 'Set filter udara luar dan dalam Sakura A-1502/A-1503 Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-01-15').toISOString(),
  },
  {
    id: 'kom-4',
    part_number: 'V-BELT-A38-KOM',
    name: 'Engine Fan Belt V-Belt Heavy Duty Tipe A38',
    brand: 'Komatsu',
    category: 'Engine',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 95000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'V-belt fan belt kipas mesin diesel Komatsu tipe A38.',
    is_fast_moving: true,
    created_at: new Date('2026-01-18').toISOString(),
  },
  {
    id: 'kom-5',
    part_number: '11065-43G01',
    name: 'Glow Plug Busi Pemanas Diesel 12V',
    brand: 'Komatsu',
    category: 'Engine',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16', 'Nissan TD27'],
    price: 240000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Busi pemanas glow plug 12V stater dingin mesin Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-01-20').toISOString(),
  },
  {
    id: 'kom-6',
    part_number: 'WATER-PUMP-KOM',
    name: 'Engine Water Pump Assembly Komatsu 4D94E / 4D98E',
    brand: 'Komatsu',
    category: 'Engine',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 1650000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Pompa air pendingin (water pump) mesin diesel Komatsu 4D94E / 4D98E.',
    is_fast_moving: true,
    created_at: new Date('2026-01-22').toISOString(),
  },
  {
    id: 'kom-7',
    part_number: 'THERMO-76-KOM',
    name: 'Engine Thermostat 76.5°C Assembly',
    brand: 'Komatsu',
    category: 'Engine',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 290000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Thermostat pengatur suhu pendingin mesin Komatsu 76.5°C.',
    is_fast_moving: true,
    created_at: new Date('2026-01-25').toISOString(),
  },
  {
    id: 'kom-8',
    part_number: 'NOZZLE-KOM',
    name: 'Fuel Injector Nozzle Solar Diesel',
    brand: 'Komatsu',
    category: 'Engine',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Nozzle injektor solar mesin Komatsu 4D94E pembakaran presisi.',
    is_fast_moving: true,
    created_at: new Date('2026-01-28').toISOString(),
  },
  {
    id: 'kom-9',
    part_number: 'PISTON-KOM',
    name: 'Engine Piston Kit Set Complete (Piston, Ring, Pin)',
    brand: 'Komatsu',
    category: 'Engine',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 2850000,
    stock_status: 'INDENT',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Set piston mesin komplit (Piston, Ring, Pin) overhaul Komatsu.',
    is_fast_moving: false,
    created_at: new Date('2026-02-01').toISOString(),
  },
  {
    id: 'kom-10',
    part_number: 'GASKET-KOM',
    name: 'Engine Gasket Overhaul Set Top & Bottom',
    brand: 'Komatsu',
    category: 'Engine',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 1450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Paking set overhaul komplit baja berlapis grafit Komatsu.',
    is_fast_moving: false,
    created_at: new Date('2026-02-02').toISOString(),
  },
  {
    id: 'kom-11',
    part_number: 'TORQUE-KOM',
    name: 'Torque Converter Assembly Automatic Transmission',
    brand: 'Komatsu',
    category: 'Engine',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 6850000,
    stock_status: 'INDENT',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Unit kopling hidrolik Torque Converter transmisi matic Komatsu.',
    is_fast_moving: false,
    created_at: new Date('2026-02-03').toISOString(),
  },
  {
    id: 'kom-12',
    part_number: 'CLUTCH-KOM',
    name: 'Transmission Clutch Disc Friction Plate',
    brand: 'Komatsu',
    category: 'Brake',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 480000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Plat kopling transmisi (friction disc) Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-02-04').toISOString(),
  },
  {
    id: 'kom-13',
    part_number: 'SEAL-TRANS-KOM',
    name: 'Automatic Transmission Repair Seal Kit',
    brand: 'Komatsu',
    category: 'Brake',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 890000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Sil kit perbaikan transmisi otomatis Powershift Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-02-05').toISOString(),
  },
  {
    id: 'kom-14',
    part_number: 'MASTER-REM-KOM',
    name: 'Brake Master Cylinder Assembly',
    brand: 'Komatsu',
    category: 'Brake',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 1450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Master rem utama presisi tinggi Komatsu FD25/FD30.',
    is_fast_moving: true,
    created_at: new Date('2026-02-06').toISOString(),
  },
  {
    id: 'kom-15',
    part_number: 'WHEEL-CYL-KOM',
    name: 'Wheel Brake Cylinder Assembly Left/Right',
    brand: 'Komatsu',
    category: 'Brake',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Silinder roda pengereman tromol depan Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-02-07').toISOString(),
  },
  {
    id: 'kom-16',
    part_number: 'BRAKE-SHOE-KOM',
    name: 'Brake Shoe Set Front Heavy Duty',
    brand: 'Komatsu',
    category: 'Brake',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 780000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Kampas rem set roda depan Komatsu FD25/FD30.',
    is_fast_moving: true,
    created_at: new Date('2026-02-08').toISOString(),
  },
  {
    id: 'kom-17',
    part_number: 'HYD-FILTER-KOM',
    name: 'Hydraulic Return Oil Filter Element',
    brand: 'Komatsu',
    category: 'Hydraulic',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 420000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Elemen filter oli hidrolik saluran balik Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-02-09').toISOString(),
  },
  {
    id: 'kom-18',
    part_number: 'TILT-SEAL-KOM',
    name: 'Tilt Cylinder Seal Kit Heavy Duty',
    brand: 'Komatsu',
    category: 'Hydraulic',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 680000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Kit seal silinder tilt kemiringan mast Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-02-10').toISOString(),
  },
  {
    id: 'kom-19',
    part_number: 'LIFT-SEAL-KOM',
    name: 'Main Lift Cylinder Seal Repair Kit',
    brand: 'Komatsu',
    category: 'Hydraulic',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 850000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Repair kit seal silinder angkat utama Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-02-11').toISOString(),
  },
  {
    id: 'kom-20',
    part_number: 'MAST-ROLLER-KOM',
    name: 'Mast Roller Bearing Heavy Duty',
    brand: 'Komatsu',
    category: 'Hydraulic',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 380000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Bearing roller pada rel tiang mast Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-02-12').toISOString(),
  },
  {
    id: 'kom-21',
    part_number: 'LH1044-KOM',
    name: 'Lifting Chain Rantai Angkat Mast 5 Meter',
    brand: 'Komatsu',
    category: 'Hydraulic',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 1750000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Rantai angkat (lifting chain) mast Komatsu LH1044 5 meter.',
    is_fast_moving: false,
    created_at: new Date('2026-02-13').toISOString(),
  },
  {
    id: 'kom-22',
    part_number: 'CW-FD30-14T',
    name: 'Chain Wheel Sprocket Gear Rantai Mast',
    brand: 'Komatsu',
    category: 'Hydraulic',
    compatible_models: ['Komatsu FD30T-16', 'Komatsu FD25T-16'],
    price: 520000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Roda puli gear rantai angkat Komatsu 3 Ton.',
    is_fast_moving: false,
    created_at: new Date('2026-02-14').toISOString(),
  },
  {
    id: 'kom-23',
    part_number: 'HYD-PUMP-KOM',
    name: 'Hydraulic Gear Pump Assembly 250 Bar',
    brand: 'Komatsu',
    category: 'Hydraulic',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 3650000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Pompa hidrolik utama (Gear pump) Komatsu 250 Bar.',
    is_fast_moving: true,
    created_at: new Date('2026-02-15').toISOString(),
  },
  {
    id: 'kom-24',
    part_number: 'CONTROL-VALVE-KOM',
    name: 'Hydraulic Control Valve Assembly 3-Spool',
    brand: 'Komatsu',
    category: 'Hydraulic',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 4950000,
    stock_status: 'INDENT',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Katup kontrol distribusi hidrolik Komatsu 3-spool.',
    is_fast_moving: false,
    created_at: new Date('2026-02-16').toISOString(),
  },
  {
    id: 'kom-25',
    part_number: 'STEER-KNUCKLE-KOM',
    name: 'Steering Axle Knuckle Left/Right',
    brand: 'Komatsu',
    category: 'Hydraulic',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 1850000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Steering knuckle setir roda belakang Komatsu.',
    is_fast_moving: false,
    created_at: new Date('2026-02-17').toISOString(),
  },
  {
    id: 'kom-26',
    part_number: 'TIE-ROD-KOM',
    name: 'Steering Tie Rod End Ball Joint',
    brand: 'Komatsu',
    category: 'Hydraulic',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 540000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Tie rod end sambungan setir Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-02-18').toISOString(),
  },
  {
    id: 'kom-27',
    part_number: 'KINGPIN-KOM',
    name: 'Steering Axle Kingpin & Bearing Repair Kit',
    brand: 'Komatsu',
    category: 'Hydraulic',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 1120000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Kit perbaikan king pin as putar roda Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-02-19').toISOString(),
  },
  {
    id: 'kom-28',
    part_number: '30209-JR',
    name: 'Front/Rear Wheel Tapered Roller Bearing',
    brand: 'Komatsu',
    category: 'Brake',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 275000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Bearing roda tapered roller presisi tinggi Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-02-20').toISOString(),
  },
  {
    id: 'kom-29',
    part_number: 'TIRE-700-12-KOM',
    name: 'Solid Forklift Tire 7.00-12 Industrial Heavy Duty',
    brand: 'Komatsu',
    category: 'Hydraulic',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 2450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Ban mati Solid Tire Komatsu 7.00-12 bebas bocor.',
    is_fast_moving: true,
    created_at: new Date('2026-02-21').toISOString(),
  },
  {
    id: 'kom-30',
    part_number: 'STARTER-KOM',
    name: 'Starter Motor Assembly 12V 2.8kW Heavy Duty',
    brand: 'Komatsu',
    category: 'Electrical',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 3200000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Motor starter 12 Volt 2.8kW torsi tinggi Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-02-22').toISOString(),
  },
  {
    id: 'kom-31',
    part_number: 'ALTERNATOR-KOM',
    name: 'Alternator Assembly 12V 50A Heavy Duty',
    brand: 'Komatsu',
    category: 'Electrical',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 2850000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Alternator dinamo cas 12V 50A Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-02-23').toISOString(),
  },
  {
    id: 'kom-32',
    part_number: 'ACCU-12V70AH',
    name: 'Forklift Heavy Duty Battery Accu 12V 70Ah',
    brand: 'Komatsu',
    category: 'Electrical',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 1350000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Aki Battery forklift 12V 70Ah CCA tinggi Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-02-24').toISOString(),
  },
  {
    id: 'kom-33',
    part_number: 'KEY-SWITCH-KOM',
    name: 'Ignition Starter Key Switch Assembly',
    brand: 'Komatsu',
    category: 'Electrical',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 350000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Kunci kontak starter komplit 2 kunci Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-02-25').toISOString(),
  },
  {
    id: 'kom-34',
    part_number: 'LAMP-LED-KOM',
    name: 'Forklift Front Headlamp & Rear Tail Lamp LED Set 24V',
    brand: 'Komatsu',
    category: 'Electrical',
    compatible_models: ['Komatsu FD25T-16', 'Komatsu FD30T-16'],
    price: 420000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Set lampu depan & belakang LED 24V Komatsu.',
    is_fast_moving: true,
    created_at: new Date('2026-02-26').toISOString(),
  },

  // ==========================================
  // 3. TOYOTA FORKLIFT SPARE PARTS
  // ==========================================
  {
    id: 'toy-1',
    part_number: 'C-1505',
    name: 'Engine Oil Filter Sakura C-1505 / Isuzu OEM',
    brand: 'Toyota',
    category: 'Filter',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 185000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80',
    description: 'Filter oli mesin Sakura C-1505 OEM Toyota 8FD25/8FD30. Menyaring kotoran pelumasan.',
    is_fast_moving: true,
    created_at: new Date('2026-01-10').toISOString(),
  },
  {
    id: 'toy-2',
    part_number: 'F-1502-TOY',
    name: 'Fuel Filter Element Sakura F-1502 / Isuzu OEM',
    brand: 'Toyota',
    category: 'Filter',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 210000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    description: 'Elemen filter bahan bakar Sakura F-1502 Toyota. Suplai solar bersih ke pompa injeksi.',
    is_fast_moving: true,
    created_at: new Date('2026-01-12').toISOString(),
  },
  {
    id: 'toy-3',
    part_number: 'A-1502-TOY',
    name: 'Air Filter Element Set Sakura A-1502/A-1503 (Outer/Inner)',
    brand: 'Toyota',
    category: 'Filter',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 320000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80',
    description: 'Set filter udara luar dan dalam Sakura A-1502/A-1503 Toyota 8FD30.',
    is_fast_moving: true,
    created_at: new Date('2026-01-15').toISOString(),
  },
  {
    id: 'toy-4',
    part_number: 'V-BELT-A38-TOY',
    name: 'Engine Fan Belt V-Belt Heavy Duty Tipe A38',
    brand: 'Toyota',
    category: 'Engine',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 95000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'V-belt fan belt kipas mesin diesel Toyota 1DZ-II.',
    is_fast_moving: true,
    created_at: new Date('2026-01-18').toISOString(),
  },
  {
    id: 'toy-5',
    part_number: '11065-TOY',
    name: 'Glow Plug Busi Pemanas Diesel 12V',
    brand: 'Toyota',
    category: 'Engine',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 240000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Busi pemanas glow plug 12V stater dingin mesin Toyota.',
    is_fast_moving: true,
    created_at: new Date('2026-01-20').toISOString(),
  },
  {
    id: 'toy-6',
    part_number: 'WATER-PUMP-TOY',
    name: 'Engine Water Pump Assembly Toyota 1DZ / 2Z',
    brand: 'Toyota',
    category: 'Engine',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 1650000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Pompa air pendingin (water pump) mesin diesel Toyota 1DZ/2Z.',
    is_fast_moving: true,
    created_at: new Date('2026-01-22').toISOString(),
  },
  {
    id: 'toy-7',
    part_number: 'THERMO-76-TOY',
    name: 'Engine Thermostat 76.5°C Assembly',
    brand: 'Toyota',
    category: 'Engine',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 290000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Thermostat pengatur suhu pendingin mesin Toyota 76.5°C.',
    is_fast_moving: true,
    created_at: new Date('2026-01-25').toISOString(),
  },
  {
    id: 'toy-8',
    part_number: '093400-5320',
    name: 'Fuel Injector Nozzle Solar Diesel',
    brand: 'Toyota',
    category: 'Engine',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Nozzle injektor solar mesin Toyota 1DZ-II pembakaran presisi.',
    is_fast_moving: true,
    created_at: new Date('2026-01-28').toISOString(),
  },
  {
    id: 'toy-9',
    part_number: 'PISTON-TOY',
    name: 'Engine Piston Kit Set Complete (Piston, Ring, Pin)',
    brand: 'Toyota',
    category: 'Engine',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 2850000,
    stock_status: 'INDENT',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Set piston mesin komplit (Piston, Ring, Pin) overhaul Toyota 1DZ.',
    is_fast_moving: false,
    created_at: new Date('2026-02-01').toISOString(),
  },
  {
    id: 'toy-10',
    part_number: 'GASKET-TOY',
    name: 'Engine Gasket Overhaul Set Top & Bottom',
    brand: 'Toyota',
    category: 'Engine',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 1450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Paking set overhaul komplit baja berlapis grafit Toyota.',
    is_fast_moving: false,
    created_at: new Date('2026-02-02').toISOString(),
  },
  {
    id: 'toy-11',
    part_number: 'TORQUE-TOY',
    name: 'Torque Converter Assembly Automatic Transmission',
    brand: 'Toyota',
    category: 'Engine',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 6850000,
    stock_status: 'INDENT',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Unit kopling hidrolik Torque Converter transmisi matic Toyota.',
    is_fast_moving: false,
    created_at: new Date('2026-02-03').toISOString(),
  },
  {
    id: 'toy-12',
    part_number: 'CLUTCH-TOY',
    name: 'Transmission Clutch Disc Friction Plate',
    brand: 'Toyota',
    category: 'Brake',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 480000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Plat kopling transmisi (friction disc) Toyota.',
    is_fast_moving: true,
    created_at: new Date('2026-02-04').toISOString(),
  },
  {
    id: 'toy-13',
    part_number: '91366-01300-KIT',
    name: 'Automatic Transmission Repair Seal Kit',
    brand: 'Toyota',
    category: 'Brake',
    compatible_models: ['Toyota 7FD30', 'Toyota 8FD30', 'Toyota 8FG25'],
    price: 890000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Sil kit perbaikan transmisi otomatis Powershift Toyota.',
    is_fast_moving: true,
    created_at: new Date('2026-02-05').toISOString(),
  },
  {
    id: 'toy-14',
    part_number: 'MASTER-REM-TOY',
    name: 'Brake Master Cylinder Assembly',
    brand: 'Toyota',
    category: 'Brake',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 1450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Master rem utama presisi tinggi Toyota 8FD25/8FD30.',
    is_fast_moving: true,
    created_at: new Date('2026-02-06').toISOString(),
  },
  {
    id: 'toy-15',
    part_number: 'WHEEL-CYL-TOY',
    name: 'Wheel Brake Cylinder Assembly Left/Right',
    brand: 'Toyota',
    category: 'Brake',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Silinder roda pengereman tromol depan Toyota.',
    is_fast_moving: true,
    created_at: new Date('2026-02-07').toISOString(),
  },
  {
    id: 'toy-16',
    part_number: '47400-30510-71',
    name: 'Brake Shoe Set Front Heavy Duty',
    brand: 'Toyota',
    category: 'Brake',
    compatible_models: ['Toyota 8FD25', 'Toyota 8FD30', 'Toyota 8FG25', 'Toyota 8FG30'],
    price: 650000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Kampas rem set roda depan forklift Toyota seri 8FD30 / 8FG30.',
    is_fast_moving: true,
    created_at: new Date('2026-02-08').toISOString(),
  },
  {
    id: 'toy-17',
    part_number: 'HYD-FILTER-TOY',
    name: 'Hydraulic Return Oil Filter Element',
    brand: 'Toyota',
    category: 'Hydraulic',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 420000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Elemen filter oli hidrolik saluran balik Toyota.',
    is_fast_moving: true,
    created_at: new Date('2026-02-09').toISOString(),
  },
  {
    id: 'toy-18',
    part_number: 'TILT-SEAL-TOY',
    name: 'Tilt Cylinder Seal Kit Heavy Duty',
    brand: 'Toyota',
    category: 'Hydraulic',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 680000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Kit seal silinder tilt kemiringan mast Toyota.',
    is_fast_moving: true,
    created_at: new Date('2026-02-10').toISOString(),
  },
  {
    id: 'toy-19',
    part_number: 'LIFT-SEAL-TOY',
    name: 'Main Lift Cylinder Seal Repair Kit',
    brand: 'Toyota',
    category: 'Hydraulic',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 850000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Repair kit seal silinder angkat utama Toyota.',
    is_fast_moving: true,
    created_at: new Date('2026-02-11').toISOString(),
  },
  {
    id: 'toy-20',
    part_number: 'MG307-2RS',
    name: 'Mast Roller Bearing Heavy Duty',
    brand: 'Toyota',
    category: 'Hydraulic',
    compatible_models: ['Toyota 7FD30', 'Toyota 8FD30', 'Toyota 8FD25'],
    price: 380000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Bearing roller pada rel tiang mast Toyota.',
    is_fast_moving: true,
    created_at: new Date('2026-02-12').toISOString(),
  },
  {
    id: 'toy-21',
    part_number: 'LH1044-TOY',
    name: 'Lifting Chain Rantai Angkat Mast 5 Meter',
    brand: 'Toyota',
    category: 'Hydraulic',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 1750000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Rantai angkat (lifting chain) mast Toyota 5 meter.',
    is_fast_moving: false,
    created_at: new Date('2026-02-13').toISOString(),
  },
  {
    id: 'toy-22',
    part_number: 'CW-TOY-14T',
    name: 'Chain Wheel Sprocket Gear Rantai Mast',
    brand: 'Toyota',
    category: 'Hydraulic',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 520000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Roda puli gear rantai angkat Toyota 3 Ton.',
    is_fast_moving: false,
    created_at: new Date('2026-02-14').toISOString(),
  },
  {
    id: 'toy-23',
    part_number: 'HYD-PUMP-TOY',
    name: 'Hydraulic Gear Pump Assembly 250 Bar',
    brand: 'Toyota',
    category: 'Hydraulic',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 3650000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Pompa hidrolik utama (Gear pump) Toyota 250 Bar.',
    is_fast_moving: true,
    created_at: new Date('2026-02-15').toISOString(),
  },
  {
    id: 'toy-24',
    part_number: 'CV-3S-FD30',
    name: 'Hydraulic Control Valve Assembly 3-Spool',
    brand: 'Toyota',
    category: 'Hydraulic',
    compatible_models: ['Toyota 7FD30', 'Toyota 8FD30', 'Toyota 8FG25'],
    price: 4950000,
    stock_status: 'INDENT',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Katup kontrol distribusi hidrolik Toyota 3-spool.',
    is_fast_moving: false,
    created_at: new Date('2026-02-16').toISOString(),
  },
  {
    id: 'toy-25',
    part_number: 'STEER-KNUCKLE-TOY',
    name: 'Steering Axle Knuckle Left/Right',
    brand: 'Toyota',
    category: 'Hydraulic',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 1850000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Steering knuckle setir roda belakang Toyota.',
    is_fast_moving: false,
    created_at: new Date('2026-02-17').toISOString(),
  },
  {
    id: 'toy-26',
    part_number: '91443-02100',
    name: 'Steering Tie Rod End Ball Joint',
    brand: 'Toyota',
    category: 'Hydraulic',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD30', 'Toyota 8FG25'],
    price: 540000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Tie rod end sambungan setir Toyota.',
    is_fast_moving: true,
    created_at: new Date('2026-02-18').toISOString(),
  },
  {
    id: 'toy-27',
    part_number: 'KINGPIN-TOY',
    name: 'Steering Axle Kingpin & Bearing Repair Kit',
    brand: 'Toyota',
    category: 'Hydraulic',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 1120000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Kit perbaikan king pin as putar roda Toyota.',
    is_fast_moving: true,
    created_at: new Date('2026-02-19').toISOString(),
  },
  {
    id: 'toy-28',
    part_number: '30209-TOY',
    name: 'Front/Rear Wheel Tapered Roller Bearing',
    brand: 'Toyota',
    category: 'Brake',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 275000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Bearing roda tapered roller presisi tinggi Toyota.',
    is_fast_moving: true,
    created_at: new Date('2026-02-20').toISOString(),
  },
  {
    id: 'toy-29',
    part_number: 'TIRE-700-12',
    name: 'Solid Forklift Tire 7.00-12 Industrial Heavy Duty',
    brand: 'Toyota',
    category: 'Hydraulic',
    compatible_models: ['Toyota 8FD25', 'Toyota 8FD30', 'TCM FD30T3', 'Komatsu FD30T-16'],
    price: 2450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Ban mati Solid Tire Toyota 7.00-12 bebas bocor.',
    is_fast_moving: true,
    created_at: new Date('2026-02-21').toISOString(),
  },
  {
    id: 'toy-30',
    part_number: '28100-23430-71',
    name: 'Starter Motor Assembly 24V Heavy Duty',
    brand: 'Toyota',
    category: 'Electrical',
    compatible_models: ['Toyota 7FD35', 'Toyota 8FD40', 'Toyota 8FD50'],
    price: 3450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Motor stater 24 Volt heavy duty untuk unit forklift Toyota.',
    is_fast_moving: true,
    created_at: new Date('2026-02-22').toISOString(),
  },
  {
    id: 'toy-31',
    part_number: 'ALTERNATOR-TOY',
    name: 'Alternator Assembly 12V 50A Heavy Duty',
    brand: 'Toyota',
    category: 'Electrical',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 2850000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Alternator dinamo cas 12V 50A Toyota.',
    is_fast_moving: true,
    created_at: new Date('2026-02-23').toISOString(),
  },
  {
    id: 'toy-32',
    part_number: 'ACCU-TOY',
    name: 'Forklift Heavy Duty Battery Accu 12V 70Ah',
    brand: 'Toyota',
    category: 'Electrical',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 1350000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Aki Battery forklift 12V 70Ah CCA tinggi Toyota.',
    is_fast_moving: true,
    created_at: new Date('2026-02-24').toISOString(),
  },
  {
    id: 'toy-33',
    part_number: 'KEY-SWITCH-TOY',
    name: 'Ignition Starter Key Switch Assembly',
    brand: 'Toyota',
    category: 'Electrical',
    compatible_models: ['Toyota 7FD25', 'Toyota 8FD25', 'Toyota 8FD30'],
    price: 350000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Kunci kontak starter komplit 2 kunci Toyota.',
    is_fast_moving: true,
    created_at: new Date('2026-02-25').toISOString(),
  },
  {
    id: 'toy-34',
    part_number: 'LAMP-LED-24V',
    name: 'Forklift Front Headlamp & Rear Tail Lamp LED Set 24V',
    brand: 'Toyota',
    category: 'Electrical',
    compatible_models: ['Toyota 7FD30', 'Toyota 8FD30', 'Toyota 8FG25'],
    price: 420000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Set lampu depan & belakang LED 24V Toyota.',
    is_fast_moving: true,
    created_at: new Date('2026-02-26').toISOString(),
  },

  // ==========================================
  // 4. TCM FORKLIFT SPARE PARTS
  // ==========================================
  {
    id: 'tcm-1',
    part_number: 'C-1505-TCM',
    name: 'Engine Oil Filter Sakura C-1505 / Isuzu OEM',
    brand: 'TCM',
    category: 'Filter',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3', 'Isuzu C240'],
    price: 185000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80',
    description: 'Filter oli mesin Sakura C-1505 OEM Isuzu C240 TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-01-10').toISOString(),
  },
  {
    id: 'tcm-2',
    part_number: 'F-1502',
    name: 'Fuel Filter Element Sakura F-1502 / Isuzu OEM',
    brand: 'TCM',
    category: 'Filter',
    compatible_models: ['TCM FD30T3', 'TCM FD25T3', 'Isuzu C240'],
    price: 210000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    description: 'Elemen filter bahan bakar Sakura F-1502 TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-01-12').toISOString(),
  },
  {
    id: 'tcm-3',
    part_number: 'A-1502-TCM',
    name: 'Air Filter Element Set Sakura A-1502/A-1503 (Outer/Inner)',
    brand: 'TCM',
    category: 'Filter',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 320000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80',
    description: 'Set filter udara luar dan dalam Sakura A-1502/A-1503 TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-01-15').toISOString(),
  },
  {
    id: 'tcm-4',
    part_number: 'V-BELT-A38-TCM',
    name: 'Engine Fan Belt V-Belt Heavy Duty Tipe A38',
    brand: 'TCM',
    category: 'Engine',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 95000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'V-belt fan belt kipas mesin diesel Isuzu C240 TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-01-18').toISOString(),
  },
  {
    id: 'tcm-5',
    part_number: '11065-TCM',
    name: 'Glow Plug Busi Pemanas Diesel 12V',
    brand: 'TCM',
    category: 'Engine',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 240000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Busi pemanas glow plug 12V stater dingin mesin TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-01-20').toISOString(),
  },
  {
    id: 'tcm-6',
    part_number: 'WATER-PUMP-TCM',
    name: 'Engine Water Pump Assembly Isuzu C240',
    brand: 'TCM',
    category: 'Engine',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 1650000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Pompa air pendingin (water pump) mesin Isuzu C240 TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-01-22').toISOString(),
  },
  {
    id: 'tcm-7',
    part_number: 'THERMO-76-TCM',
    name: 'Engine Thermostat 76.5°C Assembly',
    brand: 'TCM',
    category: 'Engine',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 290000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Thermostat pengatur suhu pendingin mesin TCM 76.5°C.',
    is_fast_moving: true,
    created_at: new Date('2026-01-25').toISOString(),
  },
  {
    id: 'tcm-8',
    part_number: 'NOZZLE-TCM',
    name: 'Fuel Injector Nozzle Solar Diesel',
    brand: 'TCM',
    category: 'Engine',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Nozzle injektor solar mesin Isuzu C240 TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-01-28').toISOString(),
  },
  {
    id: 'tcm-9',
    part_number: '5-87813-059-0',
    name: 'Engine Piston Kit Set Complete (Piston, Ring, Pin)',
    brand: 'TCM',
    category: 'Engine',
    compatible_models: ['TCM FD30T3', 'Isuzu C240'],
    price: 2850000,
    stock_status: 'INDENT',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Set piston mesin komplit (Piston, Ring, Pin) Isuzu C240 TCM.',
    is_fast_moving: false,
    created_at: new Date('2026-02-01').toISOString(),
  },
  {
    id: 'tcm-10',
    part_number: 'GASKET-TCM',
    name: 'Engine Gasket Overhaul Set Top & Bottom',
    brand: 'TCM',
    category: 'Engine',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 1450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Paking set overhaul komplit Isuzu C240 TCM.',
    is_fast_moving: false,
    created_at: new Date('2026-02-02').toISOString(),
  },
  {
    id: 'tcm-11',
    part_number: '216A2-80201',
    name: 'Torque Converter Assembly Automatic Transmission',
    brand: 'TCM',
    category: 'Engine',
    compatible_models: ['TCM FD30T3', 'TCM FD35T3S', 'TCM FG25T3'],
    price: 6850000,
    stock_status: 'INDENT',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Unit kopling hidrolik Torque Converter transmisi matic TCM 3 Ton.',
    is_fast_moving: false,
    created_at: new Date('2026-02-03').toISOString(),
  },
  {
    id: 'tcm-12',
    part_number: 'CLUTCH-TCM',
    name: 'Transmission Clutch Disc Friction Plate',
    brand: 'TCM',
    category: 'Brake',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 480000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Plat kopling transmisi (friction disc) TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-02-04').toISOString(),
  },
  {
    id: 'tcm-13',
    part_number: 'SEAL-TRANS-TCM',
    name: 'Automatic Transmission Repair Seal Kit',
    brand: 'TCM',
    category: 'Brake',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 890000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Sil kit perbaikan transmisi otomatis Powershift TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-02-05').toISOString(),
  },
  {
    id: 'tcm-14',
    part_number: 'MASTER-REM-TCM',
    name: 'Brake Master Cylinder Assembly',
    brand: 'TCM',
    category: 'Brake',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 1450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Master rem utama presisi tinggi TCM FD25/FD30.',
    is_fast_moving: true,
    created_at: new Date('2026-02-06').toISOString(),
  },
  {
    id: 'tcm-15',
    part_number: 'WHEEL-CYL-TCM',
    name: 'Wheel Brake Cylinder Assembly Left/Right',
    brand: 'TCM',
    category: 'Brake',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Silinder roda pengereman tromol depan TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-02-07').toISOString(),
  },
  {
    id: 'tcm-16',
    part_number: 'BRAKE-SHOE-TCM',
    name: 'Brake Shoe Set Front Heavy Duty',
    brand: 'TCM',
    category: 'Brake',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 780000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Kampas rem set roda depan TCM FD25/FD30.',
    is_fast_moving: true,
    created_at: new Date('2026-02-08').toISOString(),
  },
  {
    id: 'tcm-17',
    part_number: 'HYD-FILTER-TCM',
    name: 'Hydraulic Return Oil Filter Element',
    brand: 'TCM',
    category: 'Hydraulic',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 420000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Elemen filter oli hidrolik saluran balik TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-02-09').toISOString(),
  },
  {
    id: 'tcm-18',
    part_number: 'TILT-SEAL-TCM',
    name: 'Tilt Cylinder Seal Kit Heavy Duty',
    brand: 'TCM',
    category: 'Hydraulic',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 680000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Kit seal silinder tilt kemiringan mast TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-02-10').toISOString(),
  },
  {
    id: 'tcm-19',
    part_number: 'LIFT-SEAL-TCM',
    name: 'Main Lift Cylinder Seal Repair Kit',
    brand: 'TCM',
    category: 'Hydraulic',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 850000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Repair kit seal silinder angkat utama TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-02-11').toISOString(),
  },
  {
    id: 'tcm-20',
    part_number: 'MAST-ROLLER-TCM',
    name: 'Mast Roller Bearing Heavy Duty',
    brand: 'TCM',
    category: 'Hydraulic',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 380000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Bearing roller pada rel tiang mast TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-02-12').toISOString(),
  },
  {
    id: 'tcm-21',
    part_number: 'LH1044-5M',
    name: 'Lifting Chain Rantai Angkat Mast 5 Meter',
    brand: 'TCM',
    category: 'Hydraulic',
    compatible_models: ['TCM FD30T3', 'TCM FD25T3'],
    price: 1750000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Rantai angkat (lifting chain) mast TCM LH1044 5 meter.',
    is_fast_moving: false,
    created_at: new Date('2026-02-13').toISOString(),
  },
  {
    id: 'tcm-22',
    part_number: 'CW-TCM-14T',
    name: 'Chain Wheel Sprocket Gear Rantai Mast',
    brand: 'TCM',
    category: 'Hydraulic',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 520000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Roda puli gear rantai angkat TCM 3 Ton.',
    is_fast_moving: false,
    created_at: new Date('2026-02-14').toISOString(),
  },
  {
    id: 'tcm-23',
    part_number: '214A2-40201',
    name: 'Hydraulic Gear Pump Assembly 250 Bar',
    brand: 'TCM',
    category: 'Hydraulic',
    compatible_models: ['TCM FD30T3', 'TCM FD35T3S', 'TCM FG25T3'],
    price: 3650000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Pompa hidrolik utama (Gear pump) Forklift TCM 3 Ton.',
    is_fast_moving: true,
    created_at: new Date('2026-02-15').toISOString(),
  },
  {
    id: 'tcm-24',
    part_number: 'CV-3S-TCM',
    name: 'Hydraulic Control Valve Assembly 3-Spool',
    brand: 'TCM',
    category: 'Hydraulic',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 4950000,
    stock_status: 'INDENT',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Katup kontrol distribusi hidrolik TCM 3-spool.',
    is_fast_moving: false,
    created_at: new Date('2026-02-16').toISOString(),
  },
  {
    id: 'tcm-25',
    part_number: 'STEER-KNUCKLE-TCM',
    name: 'Steering Axle Knuckle Left/Right',
    brand: 'TCM',
    category: 'Hydraulic',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 1850000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Steering knuckle setir roda belakang TCM.',
    is_fast_moving: false,
    created_at: new Date('2026-02-17').toISOString(),
  },
  {
    id: 'tcm-26',
    part_number: 'TIE-ROD-TCM',
    name: 'Steering Tie Rod End Ball Joint',
    brand: 'TCM',
    category: 'Hydraulic',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 540000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Tie rod end sambungan setir TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-02-18').toISOString(),
  },
  {
    id: 'tcm-27',
    part_number: 'KINGPIN-TCM',
    name: 'Steering Axle Kingpin & Bearing Repair Kit',
    brand: 'TCM',
    category: 'Hydraulic',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 1120000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Kit perbaikan king pin as putar roda TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-02-19').toISOString(),
  },
  {
    id: 'tcm-28',
    part_number: '30209-TCM',
    name: 'Front/Rear Wheel Tapered Roller Bearing',
    brand: 'TCM',
    category: 'Brake',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 275000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Bearing roda tapered roller presisi tinggi TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-02-20').toISOString(),
  },
  {
    id: 'tcm-29',
    part_number: 'TIRE-700-12-TCM',
    name: 'Solid Forklift Tire 7.00-12 Industrial Heavy Duty',
    brand: 'TCM',
    category: 'Hydraulic',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 2450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Ban mati Solid Tire TCM 7.00-12 bebas bocor.',
    is_fast_moving: true,
    created_at: new Date('2026-02-21').toISOString(),
  },
  {
    id: 'tcm-30',
    part_number: 'STARTER-TCM',
    name: 'Starter Motor Assembly 12V 2.8kW Heavy Duty',
    brand: 'TCM',
    category: 'Electrical',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 3200000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Motor starter 12 Volt 2.8kW torsi tinggi TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-02-22').toISOString(),
  },
  {
    id: 'tcm-31',
    part_number: 'ALTERNATOR-TCM',
    name: 'Alternator Assembly 12V 50A Heavy Duty',
    brand: 'TCM',
    category: 'Electrical',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 2850000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Alternator dinamo cas 12V 50A TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-02-23').toISOString(),
  },
  {
    id: 'tcm-32',
    part_number: 'ACCU-TCM',
    name: 'Forklift Heavy Duty Battery Accu 12V 70Ah',
    brand: 'TCM',
    category: 'Electrical',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 1350000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Aki Battery forklift 12V 70Ah CCA tinggi TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-02-24').toISOString(),
  },
  {
    id: 'tcm-33',
    part_number: 'KEY-SWITCH-TCM',
    name: 'Ignition Starter Key Switch Assembly',
    brand: 'TCM',
    category: 'Electrical',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 350000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Kunci kontak starter komplit 2 kunci TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-02-25').toISOString(),
  },
  {
    id: 'tcm-34',
    part_number: 'LAMP-LED-TCM',
    name: 'Forklift Front Headlamp & Rear Tail Lamp LED Set 24V',
    brand: 'TCM',
    category: 'Electrical',
    compatible_models: ['TCM FD25T3', 'TCM FD30T3'],
    price: 420000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Set lampu depan & belakang LED 24V TCM.',
    is_fast_moving: true,
    created_at: new Date('2026-02-26').toISOString(),
  },

  // ==========================================
  // 5. MITSUBISHI FORKLIFT SPARE PARTS
  // ==========================================
  {
    id: 'mit-1',
    part_number: 'C-1505-MIT',
    name: 'Engine Oil Filter Sakura C-1505 / Isuzu OEM',
    brand: 'Mitsubishi',
    category: 'Filter',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N', 'Mitsubishi S4S'],
    price: 185000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80',
    description: 'Filter oli mesin Sakura C-1505 OEM Mitsubishi S4S/S6S.',
    is_fast_moving: true,
    created_at: new Date('2026-01-10').toISOString(),
  },
  {
    id: 'mit-2',
    part_number: 'F-1502-MIT',
    name: 'Fuel Filter Element Sakura F-1502 / Isuzu OEM',
    brand: 'Mitsubishi',
    category: 'Filter',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N', 'Mitsubishi S4S'],
    price: 210000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    description: 'Elemen filter bahan bakar Sakura F-1502 Mitsubishi S4S.',
    is_fast_moving: true,
    created_at: new Date('2026-01-12').toISOString(),
  },
  {
    id: 'mit-3',
    part_number: 'A-1502-MIT',
    name: 'Air Filter Element Set Sakura A-1502/A-1503 (Outer/Inner)',
    brand: 'Mitsubishi',
    category: 'Filter',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 320000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800&auto=format&fit=crop&q=80',
    description: 'Set filter udara luar dan dalam Sakura A-1502/A-1503 Mitsubishi.',
    is_fast_moving: true,
    created_at: new Date('2026-01-15').toISOString(),
  },
  {
    id: 'mit-4',
    part_number: 'V-BELT-A38',
    name: 'Engine Fan Belt V-Belt Heavy Duty Tipe A38',
    brand: 'Mitsubishi',
    category: 'Engine',
    compatible_models: ['Mitsubishi S4S', 'Mitsubishi S6S', 'Mitsubishi FD30N'],
    price: 95000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'V-belt fan belt kipas mesin diesel Mitsubishi S4S/S6S.',
    is_fast_moving: true,
    created_at: new Date('2026-01-18').toISOString(),
  },
  {
    id: 'mit-5',
    part_number: '11065-MIT',
    name: 'Glow Plug Busi Pemanas Diesel 12V',
    brand: 'Mitsubishi',
    category: 'Engine',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N', 'Mitsubishi S4S'],
    price: 240000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Busi pemanas glow plug 12V stater dingin mesin Mitsubishi.',
    is_fast_moving: true,
    created_at: new Date('2026-01-20').toISOString(),
  },
  {
    id: 'mit-6',
    part_number: 'WATER-PUMP-MIT',
    name: 'Engine Water Pump Assembly Mitsubishi S4S / S6S',
    brand: 'Mitsubishi',
    category: 'Engine',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N', 'Mitsubishi S4S'],
    price: 1650000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Pompa air pendingin (water pump) mesin diesel Mitsubishi S4S.',
    is_fast_moving: true,
    created_at: new Date('2026-01-22').toISOString(),
  },
  {
    id: 'mit-7',
    part_number: 'THERMO-76-MIT',
    name: 'Engine Thermostat 76.5°C Assembly',
    brand: 'Mitsubishi',
    category: 'Engine',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 290000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Thermostat pengatur suhu pendingin mesin Mitsubishi 76.5°C.',
    is_fast_moving: true,
    created_at: new Date('2026-01-25').toISOString(),
  },
  {
    id: 'mit-8',
    part_number: 'NOZZLE-MIT',
    name: 'Fuel Injector Nozzle Solar Diesel',
    brand: 'Mitsubishi',
    category: 'Engine',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N', 'Mitsubishi S4S'],
    price: 450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Nozzle injektor solar mesin Mitsubishi S4S pembakaran presisi.',
    is_fast_moving: true,
    created_at: new Date('2026-01-28').toISOString(),
  },
  {
    id: 'mit-9',
    part_number: 'PISTON-MIT',
    name: 'Engine Piston Kit Set Complete (Piston, Ring, Pin)',
    brand: 'Mitsubishi',
    category: 'Engine',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N', 'Mitsubishi S4S'],
    price: 2850000,
    stock_status: 'INDENT',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Set piston mesin komplit (Piston, Ring, Pin) overhaul Mitsubishi S4S.',
    is_fast_moving: false,
    created_at: new Date('2026-02-01').toISOString(),
  },
  {
    id: 'mit-10',
    part_number: 'ME014833',
    name: 'Engine Gasket Overhaul Set Top & Bottom',
    brand: 'Mitsubishi',
    category: 'Engine',
    compatible_models: ['Mitsubishi S4S', 'Mitsubishi S6S', 'Mitsubishi FD30N'],
    price: 1450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?w=800&auto=format&fit=crop&q=80',
    description: 'Paking set (top & bottom overhaul) berbahan baja berlapis grafit Mitsubishi S4S & S6S.',
    is_fast_moving: false,
    created_at: new Date('2026-02-02').toISOString(),
  },
  {
    id: 'mit-11',
    part_number: 'TORQUE-MIT',
    name: 'Torque Converter Assembly Automatic Transmission',
    brand: 'Mitsubishi',
    category: 'Engine',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 6850000,
    stock_status: 'INDENT',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Unit kopling hidrolik Torque Converter transmisi matic Mitsubishi.',
    is_fast_moving: false,
    created_at: new Date('2026-02-03').toISOString(),
  },
  {
    id: 'mit-12',
    part_number: 'CLUTCH-MIT',
    name: 'Transmission Clutch Disc Friction Plate',
    brand: 'Mitsubishi',
    category: 'Brake',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 480000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Plat kopling transmisi (friction disc) Mitsubishi.',
    is_fast_moving: true,
    created_at: new Date('2026-02-04').toISOString(),
  },
  {
    id: 'mit-13',
    part_number: 'SEAL-TRANS-MIT',
    name: 'Automatic Transmission Repair Seal Kit',
    brand: 'Mitsubishi',
    category: 'Brake',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 890000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Sil kit perbaikan transmisi otomatis Powershift Mitsubishi.',
    is_fast_moving: true,
    created_at: new Date('2026-02-05').toISOString(),
  },
  {
    id: 'mit-14',
    part_number: 'MASTER-REM-MIT',
    name: 'Brake Master Cylinder Assembly',
    brand: 'Mitsubishi',
    category: 'Brake',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 1450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Master rem utama presisi tinggi Mitsubishi FD25N/FD30N.',
    is_fast_moving: true,
    created_at: new Date('2026-02-06').toISOString(),
  },
  {
    id: 'mit-15',
    part_number: 'WHEEL-CYL-MIT',
    name: 'Wheel Brake Cylinder Assembly Left/Right',
    brand: 'Mitsubishi',
    category: 'Brake',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Silinder roda pengereman tromol depan Mitsubishi.',
    is_fast_moving: true,
    created_at: new Date('2026-02-07').toISOString(),
  },
  {
    id: 'mit-16',
    part_number: 'BRAKE-SHOE-MIT',
    name: 'Brake Shoe Set Front Heavy Duty',
    brand: 'Mitsubishi',
    category: 'Brake',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 780000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Kampas rem set roda depan Mitsubishi FD25N/FD30N.',
    is_fast_moving: true,
    created_at: new Date('2026-02-08').toISOString(),
  },
  {
    id: 'mit-17',
    part_number: 'HYD-FILTER-MIT',
    name: 'Hydraulic Return Oil Filter Element',
    brand: 'Mitsubishi',
    category: 'Hydraulic',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 420000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Elemen filter oli hidrolik saluran balik Mitsubishi.',
    is_fast_moving: true,
    created_at: new Date('2026-02-09').toISOString(),
  },
  {
    id: 'mit-18',
    part_number: 'TILT-SEAL-MIT',
    name: 'Tilt Cylinder Seal Kit Heavy Duty',
    brand: 'Mitsubishi',
    category: 'Hydraulic',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 680000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Kit seal silinder tilt kemiringan mast Mitsubishi.',
    is_fast_moving: true,
    created_at: new Date('2026-02-10').toISOString(),
  },
  {
    id: 'mit-19',
    part_number: 'LIFT-SEAL-MIT',
    name: 'Main Lift Cylinder Seal Repair Kit',
    brand: 'Mitsubishi',
    category: 'Hydraulic',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 850000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Repair kit seal silinder angkat utama Mitsubishi.',
    is_fast_moving: true,
    created_at: new Date('2026-02-11').toISOString(),
  },
  {
    id: 'mit-20',
    part_number: 'MAST-ROLLER-MIT',
    name: 'Mast Roller Bearing Heavy Duty',
    brand: 'Mitsubishi',
    category: 'Hydraulic',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 380000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Bearing roller pada rel tiang mast Mitsubishi.',
    is_fast_moving: true,
    created_at: new Date('2026-02-12').toISOString(),
  },
  {
    id: 'mit-21',
    part_number: 'LH1044-MIT',
    name: 'Lifting Chain Rantai Angkat Mast 5 Meter',
    brand: 'Mitsubishi',
    category: 'Hydraulic',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 1750000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Rantai angkat (lifting chain) mast Mitsubishi LH1044 5 meter.',
    is_fast_moving: false,
    created_at: new Date('2026-02-13').toISOString(),
  },
  {
    id: 'mit-22',
    part_number: 'CW-MIT-14T',
    name: 'Chain Wheel Sprocket Gear Rantai Mast',
    brand: 'Mitsubishi',
    category: 'Hydraulic',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 520000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Roda puli gear rantai angkat Mitsubishi 3 Ton.',
    is_fast_moving: false,
    created_at: new Date('2026-02-14').toISOString(),
  },
  {
    id: 'mit-23',
    part_number: 'HYD-PUMP-MIT',
    name: 'Hydraulic Gear Pump Assembly 250 Bar',
    brand: 'Mitsubishi',
    category: 'Hydraulic',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 3650000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Pompa hidrolik utama (Gear pump) Mitsubishi 250 Bar.',
    is_fast_moving: true,
    created_at: new Date('2026-02-15').toISOString(),
  },
  {
    id: 'mit-24',
    part_number: 'CV-3S-MIT',
    name: 'Hydraulic Control Valve Assembly 3-Spool',
    brand: 'Mitsubishi',
    category: 'Hydraulic',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 4950000,
    stock_status: 'INDENT',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Katup kontrol distribusi hidrolik Mitsubishi 3-spool.',
    is_fast_moving: false,
    created_at: new Date('2026-02-16').toISOString(),
  },
  {
    id: 'mit-25',
    part_number: 'STEER-KNUCKLE-MIT',
    name: 'Steering Axle Knuckle Left/Right',
    brand: 'Mitsubishi',
    category: 'Hydraulic',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 1850000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Steering knuckle setir roda belakang Mitsubishi.',
    is_fast_moving: false,
    created_at: new Date('2026-02-17').toISOString(),
  },
  {
    id: 'mit-26',
    part_number: 'TIE-ROD-MIT',
    name: 'Steering Tie Rod End Ball Joint',
    brand: 'Mitsubishi',
    category: 'Hydraulic',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 540000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Tie rod end sambungan setir Mitsubishi.',
    is_fast_moving: true,
    created_at: new Date('2026-02-18').toISOString(),
  },
  {
    id: 'mit-27',
    part_number: 'KINGPIN-MIT',
    name: 'Steering Axle Kingpin & Bearing Repair Kit',
    brand: 'Mitsubishi',
    category: 'Hydraulic',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 1120000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Kit perbaikan king pin as putar roda Mitsubishi.',
    is_fast_moving: true,
    created_at: new Date('2026-02-19').toISOString(),
  },
  {
    id: 'mit-28',
    part_number: '30209-MIT',
    name: 'Front/Rear Wheel Tapered Roller Bearing',
    brand: 'Mitsubishi',
    category: 'Brake',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 275000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    description: 'Bearing roda tapered roller presisi tinggi Mitsubishi.',
    is_fast_moving: true,
    created_at: new Date('2026-02-20').toISOString(),
  },
  {
    id: 'mit-29',
    part_number: 'TIRE-700-12-MIT',
    name: 'Solid Forklift Tire 7.00-12 Industrial Heavy Duty',
    brand: 'Mitsubishi',
    category: 'Hydraulic',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 2450000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    description: 'Ban mati Solid Tire Mitsubishi 7.00-12 bebas bocor.',
    is_fast_moving: true,
    created_at: new Date('2026-02-21').toISOString(),
  },
  {
    id: 'mit-30',
    part_number: 'STARTER-MIT',
    name: 'Starter Motor Assembly 12V 2.8kW Heavy Duty',
    brand: 'Mitsubishi',
    category: 'Electrical',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N', 'Mitsubishi S4S'],
    price: 3200000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Motor starter 12 Volt 2.8kW torsi tinggi Mitsubishi S4S.',
    is_fast_moving: true,
    created_at: new Date('2026-02-22').toISOString(),
  },
  {
    id: 'mit-31',
    part_number: 'ALTERNATOR-MIT',
    name: 'Alternator Assembly 12V 50A Heavy Duty',
    brand: 'Mitsubishi',
    category: 'Electrical',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N', 'Mitsubishi S4S'],
    price: 2850000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Alternator dinamo cas 12V 50A Mitsubishi S4S.',
    is_fast_moving: true,
    created_at: new Date('2026-02-23').toISOString(),
  },
  {
    id: 'mit-32',
    part_number: 'ACCU-MIT',
    name: 'Forklift Heavy Duty Battery Accu 12V 70Ah',
    brand: 'Mitsubishi',
    category: 'Electrical',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 1350000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Aki Battery forklift 12V 70Ah CCA tinggi Mitsubishi.',
    is_fast_moving: true,
    created_at: new Date('2026-02-24').toISOString(),
  },
  {
    id: 'mit-33',
    part_number: 'KEY-SWITCH-MIT',
    name: 'Ignition Starter Key Switch Assembly',
    brand: 'Mitsubishi',
    category: 'Electrical',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 350000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Kunci kontak starter komplit 2 kunci Mitsubishi.',
    is_fast_moving: true,
    created_at: new Date('2026-02-25').toISOString(),
  },
  {
    id: 'mit-34',
    part_number: 'LAMP-LED-MIT',
    name: 'Forklift Front Headlamp & Rear Tail Lamp LED Set 24V',
    brand: 'Mitsubishi',
    category: 'Electrical',
    compatible_models: ['Mitsubishi FD25N', 'Mitsubishi FD30N'],
    price: 420000,
    stock_status: 'READY',
    image_url: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&auto=format&fit=crop&q=80',
    description: 'Set lampu depan & belakang LED 24V Mitsubishi.',
    is_fast_moving: true,
    created_at: new Date('2026-02-26').toISOString(),
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1',
    order_code: 'ORD-20260901-1029',
    customer_name: 'Bambang Supriyanto',
    customer_phone: '081298765432',
    customer_email: 'bambang.logistik@ptmandiri.com',
    shipping_address: 'Kawasan Industri Jababeka V Blok C-12, Cikarang, Bekasi',
    payment_method: 'BANK_TRANSFER',
    payment_proof_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&auto=format&fit=crop&q=80',
    order_status: 'VERIFIED',
    total_amount: 1135000,
    created_at: new Date('2026-09-01T09:30:00Z').toISOString(),
    items: [
      {
        id: 'item-1',
        order_id: 'ord-1',
        product_id: 'cat-1',
        quantity: 1,
        price_at_purchase: 185000,
        product: INITIAL_PRODUCTS[0],
      },
      {
        id: 'item-2',
        order_id: 'ord-1',
        product_id: 'cat-16',
        quantity: 1,
        price_at_purchase: 780000,
        product: INITIAL_PRODUCTS[15],
      },
    ],
  },
  {
    id: 'ord-2',
    order_code: 'ORD-20260902-5510',
    customer_name: 'Hendra Gunawan',
    customer_phone: '081388776655',
    customer_email: 'hendra@tambangmitra.co.id',
    shipping_address: 'Worksite PT Tambang Mitra, Jl. Pelabuhan Ratu No 44, Balikpapan',
    payment_method: 'CBD',
    payment_proof_url: undefined,
    order_status: 'PENDING',
    total_amount: 3200000,
    created_at: new Date('2026-09-02T08:15:00Z').toISOString(),
    items: [
      {
        id: 'item-3',
        order_id: 'ord-2',
        product_id: 'cat-30',
        quantity: 1,
        price_at_purchase: 3200000,
        product: INITIAL_PRODUCTS[29],
      },
    ],
  },
];

export const INITIAL_INQUIRIES: EmergencyInquiry[] = [
  {
    id: 'inq-1',
    customer_name: 'Dedi Kurniawan (Site Supervisor)',
    whatsapp_number: '081909887766',
    machine_model: 'Forklift Toyota 8FD30 (Serial #8FD30-60291)',
    description: 'Unit matikan mendadak saat angkut kontainer. Kebocoran oli hidrolik hebat dari seal pompa lift utama.',
    photo_urls: [
      'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    ],
    status: 'NEW',
    created_at: new Date('2026-09-02T09:45:00Z').toISOString(),
  },
  {
    id: 'inq-2',
    customer_name: 'Rudi Hartono',
    whatsapp_number: '081233445566',
    machine_model: 'Excavator Komatsu PC200-8',
    description: 'Filter solar tersumbat di tengah proyek pematangan tanah tambang. Membutuhkan pengiriman darurat 2 jam.',
    photo_urls: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    ],
    status: 'CONTACTED',
    created_at: new Date('2026-09-01T14:20:00Z').toISOString(),
  },
];
